#pragma once
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include <glm/glm.hpp>
#include "Window/window.h"
#include "Color.h"
#include <../libs/LASzip/dll/laszip_api.h>
#include <iostream>
#include <sstream>
#include <fstream>
#include <Windows.h>
#include <vector>
#include <string>
#include <memory>
#include <functional>
#include <glm/ext/quaternion_geometric.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

